---
apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.resource }}-service
spec:
  selector:
    app: {{ cookiecutter.resource }}-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: web
