---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ cookiecutter.resource }}-service
  annotations:
    iam.gke.io/gcp-service-account: {{ cookiecutter.resource }}-service@kinetic-dryad-364616.iam.gserviceaccount.com

# gcloud iam service-accounts create {{ cookiecutter.resource }}-service \
#   --description="Manage resources for {{ cookiecutter.resource }}-service" \
#   --display-name="{{ cookiecutter.resource | capitalize }} Service"

# gcloud iam service-accounts add-iam-policy-binding \
#   --role="roles/iam.workloadIdentityUser" \
#   --member="serviceAccount:kinetic-dryad-364616.svc.id.goog[develop/{{ cookiecutter.resource }}-service]" \
#   {{ cookiecutter.resource }}-service@kinetic-dryad-364616.iam.gserviceaccount.com

# gcloud sql databases create {{ cookiecutter.resourcePlural }} --instance={{ cookiecutter.resource }}-service-db
