apiVersion: batch/v1
kind: Job
metadata:
  name: {{ cookiecutter.resource }}-service-migrations
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccountName: {{ cookiecutter.resource }}-service
      restartPolicy: Never
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: migrations
          image: ghcr.io/compada/{{ cookiecutter.resource }}-service:{{ cookiecutter.most_recent_image_tag }} # {"$imagepolicy": "flux-system:{{ cookiecutter.resource }}-service"}
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ cookiecutter.resource }}-service-config-4bhcmt5d58
            - secretRef:
                name: {{ cookiecutter.resource }}-service-db-auth
          env:
            - name: DATABASE_URL
              value: "postgres://$(PGUSER):$(PGPASSWORD)@localhost:$(PGPORT)/$(PGDATABASE)"
          command: ["npx"]
          args: ["graphile-migrate", "migrate"]
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.2.0
          imagePullPolicy: IfNotPresent
          args:
            - "--structured-logs"
            - "--port=5432"
            - "kinetic-dryad-364616:us-west1:mono-db"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits: {}
